const questions = {
    "성경 1": { question: "바벨론에서 사자굴에 들어간 인물은?", answer: "다니엘" },
    "성경 2": { question: "예수님이 광야에서 시험받으셨을 때 금식한 기간은 며칠인가요?", answer: "40일" },
    "성경 3": { question: "시편은 총 몇 장인가요?", answer: "150장" },
    "성경 4": { question: "예수님이 태어나신 마을은?", answer: "베들레헴" },
    "예삶 1": { question: "둘로스 사역 팀장 이름 3명 말하기!", answer: "팀장 3명 말하기" },
    "예삶 2": { question: "예삶 목희진 전도사님들의 성함을 모두 말하기!", answer: "공병주 전도사님, 최요셉 전도사님, 이형석 전도사님" },
    "예삶 3": { question: "금요일 예배 FFN은 무엇의 줄임말?", answer: "Family Friday Night" },
    "베델 1": { question: "교회 카페에서 파는 김밥 한줄의 가격은?", answer: "$5" },
    "베델 2": { question: "2025년 베델교회에 테마는?", answer: "\"여전히 Jesus Alone\"" },
    "수도 1": { question: "인도의 수도는?", answer: "뉴델리" },
    "수도 2": { question: "핀란드의 수도는?", answer: "헬싱키" },
    "수도 3": { question: "호주의 수도는?", answer: "캔버라" },
    "음식 1": { question: "이탈리아의 전통적인 디저트로, 커피와 마스카포네 치즈를 이용한 이 음식은?", answer: "티라미수" },
    "음식 2": { question: "감자튀김은 어느 나라에서 유래되었나요?", answer: "벨기에" },
    "음식 3": { question: "파인애플은 나무에서 자란다. (O/X)", answer: "X, 땅에서 나는 풀 종류입니다." },
    "국기 1": { image: require("./pictures/필리핀_국기.png"), answer: "필리핀" },
    "국기 2": { image: require("./pictures/아일랜드_국기.png"), answer: "아일랜드" },
    "인물 1": { image: require("./pictures/손석구.jpg"), answer: "손석구" },
    "인물 2": { image: require("./pictures/호날두.jpg"), answer: "크리스티아누 호날두" },
    "인물 3": { image: require("./pictures/마틴_루더_킹.jpg"), answer: "마틴 루더 킹" },
    "영화 1": { question: "애니메이션 \"인사이드 아웃\"에 나오는 주요 감정 5명의 이름은?", answer: "기쁨이, 슬픔이, 버럭이, 소심이, 까칠이" },
    "영화 2": { question: "다음 영화 장면의 대사를 맞추세요.", image: require("./pictures/싱글이야.jpeg"), answer: "어, 아직 싱글이야" },
    "장소 1": { image: require("./pictures/타지마할.jpeg"), answer: "타지마할" },
    "장소 2": { question: " 프랑스 파리에 있는 이 유리 피라미드는 세계적인 박물관의 입구로 사용되는 이곳은?", answer: "루브르 박물관" },
    "장소 3": { question: "세계에서 가장 높은 건물로, 부르즈 할리파가 위치한 도시는?", answer: "두바이" },
    "순발력 1": { question: "중극집 음식 다섯가지 말하기!", answer: "짜장면, 짬봉, 볶음밥, 유산슬, 탕수육, 등등..."},
    "순발력 2": { question: "의사 말고 \"사\"로 끝나는 직업 다섯가지 대기!", answer: "변호사, 목사, 간호사, 검사, 강사, 등등..."},
    "순발력 3": { question: "장미 빼고 꽃 이름 5가지!", answer: "민들레, 무궁화, 진달래, 백합, 튤립, 등등..."},
    "역사 1": { question: "대한민국의 첫 번째 대통령은 누구일까요?", answer: "이승만" },
    "역사 2": { question: "인류 최초로 달에 착륙한 사람은 누구일까요?", answer: "닐 암스트" },
    "역사 3": { question: "자유의 여신상은 어느 나라가 미국에게 선물했을까요?", answer: "프랑스" },
    "심리 1": { question: "사람이 첫인상을 형성하는 데 걸리는 시간은?", answer: "7초" },
    "심리 2": {
        question: "\"인지 부조화\"란 어떤 심리 현상을 말할까?\nA. 기억과 현실이 일치하지 않는 혼란\nB. 자신의 행동과 신념이 충돌할 때 생기는 불편함\nC. 언어적 표현과 표정이 다른 상황\nD. 타인의 행동을 자신과 비교하려는 심리",
        answer: "정답 B"
    },
    "밈 1": { image: require("./pictures/꽁꽁.jpg"), answer: "꽁꽁 얼어붙은 한강 위로 고양이가 걸어다닙니다" },
    "밈 2": { image: require("./pictures/사과해요.jpg"), answer: "사과해요 나한테!"},
    "동물 1": { question: "세계에서 가장 큰 설치류인 이 동물은?", answer: "카피바라" },
    "동물 2": { question: "캥거루는 절대 이 행동을 하지 못한다. 어떤 행동일까?", answer: "뒤로 걷기" },
    "동물 3": { question: "말은 서서도 잠을 잘 수 있다 (O/X)", answer: "O, 잘 수 있다" },
    "로고 1": { image: require("./pictures/cdg.jpg"), answer: "꼼데가르송"},
    "로고 2": { image: require("./pictures/nvidia.jpg"), answer: "엔비디아"},
    "로고 3": { image: require("./pictures/audi.png"), answer: "아우디"},
    "로고 4": { image: require("./pictures/젤리캣.jpg"), answer: "젤리캣"},
    "논리 1" : {image: require("./pictures/논리1.png"), answer: require("./pictures/논리1_정답.png")},
    "논리 2" : {image: require("./pictures/논리2.png"), answer: "가위바위보"},
    "속담 1": { question: "\"모로가도 __ 만 가면 된다.\"", answer: "서울" },
    "속담 2": { question: "\"개천에서 __난다\"", answer: "용" },
    "과학 1": { question: "사람이 들이마시는 공기에서 가장 많은 비율을 차지하는 기체는?", answer: "질소 (nitrogen)" },
    "과학 2": { question: "인체의 뼈는 총 몇 개일까? (성인 기준)", answer: "206개" },
    "과학 3": { question: "지구에서 가장 깊은 바다는 어디일까?", answer: "마리아나 해구" },
};

const topics = Object.keys(questions);

export { topics, questions };